// Auto-generated by gitrev.cmd - DO NOT EDIT
#ifndef BUILDNUMBER_H
#define BUILDNUMBER_H

#define BUILD_NUMBER 14
#define BUILD_NUMBER_STR "14"
#define COMMIT_HASH "94e4202"
#define BUILD_TIME_UTC "2026-04-07 07:40:17 UTC"
#define BUILD_HOST "NA"

#endif // BUILDNUMBER_H
